plugins {
    id 'org.jetbrains.kotlin.jvm'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation project(":core")
    implementation "org.joml:joml:1.10.5"

    implementation platform("org.lwjgl:lwjgl-bom:3.3.3")
    implementation "org.lwjgl:lwjgl"
    implementation "org.lwjgl:lwjgl-glfw"
    implementation "org.lwjgl:lwjgl-opengl"

    runtimeOnly "org.lwjgl:lwjgl::natives-windows"
    runtimeOnly "org.lwjgl:lwjgl-glfw::natives-windows"
    runtimeOnly "org.lwjgl:lwjgl-opengl::natives-windows"
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
}

kotlin {
    compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_21
    }
}

tasks.register("runRenderTestApp", JavaExec) {
    group = "application"
    description = "Runs the standalone render test app"
    classpath = sourceSets.main.runtimeClasspath
    mainClass = "sweetie.evaware.test.RenderTestApp"
}
