pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		mavenCentral()
		gradlePluginPortal()
	}
}

rootProject.name = 'Luma'

include 'api'
include 'core-gl'
include 'vulkan-blaze3d-wrapper'
include 'shader-translator'
include 'minecraft-render-library'
include 'minecraft-implementation'
include 'developer-tools'
include 'standalone-app'
include 'benchmarks'
