plugins {
    id 'net.fabricmc.fabric-loom'
    id 'org.jetbrains.kotlin.jvm'
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = "luma-minecraft-render-library"
}

repositories {
    mavenCentral()
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
    implementation "net.fabricmc:fabric-language-kotlin:${project.fabric_kotlin_version}"

    api project(":api")
    implementation project(":core-gl")
    implementation project(":vulkan-blaze3d-wrapper")
    implementation project(":shader-translator")
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 25
}

kotlin {
    compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_25
    }
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            groupId = project.maven_group
            artifactId = "minecraft-render-library"
            version = project.mod_version
        }
    }
}
