plugins {
    id 'org.jetbrains.kotlin.jvm'
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

repositories {
    mavenCentral()
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib"

    implementation platform("org.lwjgl:lwjgl-bom:3.3.3")
    implementation "org.lwjgl:lwjgl"
    implementation "org.lwjgl:lwjgl-glfw"
    implementation "org.lwjgl:lwjgl-opengl"

    implementation "org.joml:joml:1.10.5"
    implementation "org.slf4j:slf4j-api:2.0.12"

    testImplementation "org.jetbrains.kotlin:kotlin-test"
    testRuntimeOnly "org.lwjgl:lwjgl::natives-windows"
    testRuntimeOnly "org.lwjgl:lwjgl-glfw::natives-windows"
    testRuntimeOnly "org.lwjgl:lwjgl-opengl::natives-windows"
    testRuntimeOnly "org.lwjgl:lwjgl::natives-linux"
    testRuntimeOnly "org.lwjgl:lwjgl-glfw::natives-linux"
    testRuntimeOnly "org.lwjgl:lwjgl-opengl::natives-linux"
    testRuntimeOnly "org.lwjgl:lwjgl::natives-macos"
    testRuntimeOnly "org.lwjgl:lwjgl-glfw::natives-macos"
    testRuntimeOnly "org.lwjgl:lwjgl-opengl::natives-macos"
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
}

kotlin {
    compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_21
    }
}

java {
    withSourcesJar()
    withJavadocJar()
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            groupId = project.maven_group
            artifactId = "luma"
            version = project.mod_version
        }
    }

    repositories {
        def ghRepo = System.getenv("GITHUB_REPOSITORY")
        if (ghRepo != null) {
            maven {
                name = "GitHubPackages"
                url = "https://maven.pkg.github.com/${ghRepo}"
                credentials {
                    username = System.getenv("GITHUB_ACTOR") ?: project.findProperty("systemProp.gpr.user")
                    password = System.getenv("GITHUB_TOKEN") ?: project.findProperty("systemProp.gpr.token")
                }
            }
        }
    }
}
