plugins {
    id 'org.jetbrains.kotlin.jvm'
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

repositories {
    mavenCentral()
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib"

    implementation platform("org.lwjgl:lwjgl-bom:${project.lwjgl_version}")
    implementation "org.lwjgl:lwjgl"

    implementation "org.joml:joml:${project.joml_version}"
    implementation "org.slf4j:slf4j-api:2.0.12"

    testRuntimeOnly "org.lwjgl:lwjgl::natives-windows"
    testRuntimeOnly "org.lwjgl:lwjgl::natives-linux"
    testRuntimeOnly "org.lwjgl:lwjgl::natives-macos"

    testImplementation "org.jetbrains.kotlin:kotlin-test"
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 25
}

kotlin {
    compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_25
    }
}

java {
    withSourcesJar()
    withJavadocJar()
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            groupId = project.maven_group
            artifactId = "luma-api"
            version = project.mod_version
        }
    }
}
